//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conwin.GPSDAGL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Conwin.EntityFramework;
    
    public partial class DC_GPSJCDAGLEntities : DbContext
    {
        public DC_GPSJCDAGLEntities()
            : base("name=DC_GPSJCDAGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseEntity> BaseEntitySet { get; set; }
    }
}
